name: postgres-stop

on:
  workflow_dispatch:
  schedule:
  - cron:  '30 23 * * *'

jobs:
  stop:
    runs-on: ubuntu-latest
    steps:
    
    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show
    
    - name: start postgres flex
      run: |
        az postgres flexible-server stop --resource-group learn-resources01 --name learn-postgres
